apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfc-agent
  namespace: tfc
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tfc-agent
  template:
    metadata:
      labels:
        app: tfc-agent
    spec:
      containers:
      - image: jamiewri/tfc-agent-kubernetes:1.4
        name: tfc-agent
        env:
        - name: TFC_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              key: tfc-token
              name: tfc-token
              optional: false
        - name: TFC_AGENT_NAME
          value: tfc-agent-kubernetes
        - name: TFC_AGENT_LOG_LEVEL
          value: INFO
        - name: TFC_AGENT_SINGLE
          value: "true"
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: token
      restartPolicy: Always
      serviceAccountName: tfc-agent
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 600
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 600
              audience: vault
