global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.12.1"

  serviceAccount:
    create: false
    name: "vault-cluster-admin"

  affinity: {}

  readinessProbe:
    enabled: false
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    initialDelaySeconds: 60

  dev:
    enabled: true
    devRootToken: "root"
